spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/htoh?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/ # change default templates folder
    suffix: .html
    check-template-location: true
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:\UPLOAD_FILES
      max-file-size: 100MB
      max-request-size: 100MB
jpa:
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  open-in-view: false
  show-sql: true
  hibernate:
    format_sql: true
    ddl-auto: create

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE